spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
#  mvc:
#    static-path-pattern: /res/**
##  web:
##    resources:
##      static-locations: [classpath:/haha/]